import Head from 'next/head';
import Image from 'next/image';
import phaseOne from '../public/Screen Shot 2022-11-29 at 3.52.06 PM.png'
import phaseTwo from '../public/Screen Shot 2022-11-29 at 3.54.00 PM.png'
import chyren from '../public/Screen Shot 2022-12-01 at 7.32.34 PM.png'
import Dakota from '../public/Screen Shot 2022-12-01 at 7.34.43 PM.png'
import Shoes from '../public/Screen Shot 2022-12-01 at 7.51.34 PM.png'
import shopButtafly from '../public/Screen Shot 2022-12-01 at 7.47.16 PM.png'
import phaseForth from '../public/Screen Shot 2022-11-29 at 3.56.46 PM.png'
import mikel from '../public/Screen Shot 2022-12-01 at 10.56.56 AM.png';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Mike Dwyer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10'>
        <section className="h-screen">
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className='text-xl'>Mike Dwyer</h1>
            <ul className='flec items-center'>
              <li>
                <BsFillMoonStarsFill className='cursor-pointer text-2xl'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-600 to-sky-300 text-white px-4 py-2 rounded-md ml-8' href='#'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl text-teal-500 font-medium'>Michael Dwyer</h2>
            <h3 className='text-2xl py-2'>Developer, Videographer, Photographer, and Graphic Designer</h3>
            <p className='text-md py-5 leading-8 text-gray-800'>Freelancer that provides services for programming, media coverage, and graphic designing needs. Join me down below and let's lock in some work!</p>
          </div>
          <div className='flex justify-items-center text-gray-800'>
            <div className='flex justify-items-center mx-auto text-5xl gap-16 pb-3'>
              <AiFillInstagram className='cursor-pointer'/>
              <AiFillLinkedin className='cursor-pointer'/>
              <AiFillYoutube className='cursor-pointer'/>
            </div>
          </div>
          <div className='relative w-80 h-80 mt-15 mx-auto'>
            <Image className='rounded-full' src={mikel} layout='fill' objectFit='cover'/>
          </div>
        </section>

        <section>
          <div>
            <h3 className='text-3xl py-1'>
              Services I Offer
            </h3>
            <p className='text-md py-20 leading-8 text-gray-800'>
              I have over 7 years of experience doing videography and photography for many different events. I've set-up live streams, work as grip on sets, have hands-on knowledge using all different types of cameras, and still growing my knoweldge. I graduated from Flatiron School in NYC with knowledge in HTML, Javascript, React, Sinatra, SQL, and Ruby on Rails. I use everything in the Adobe Suite for editing pictures, video, and graphic design work.
            </p>
          </div>
          <div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto rounded' src={phaseOne} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Phase One Project
              </h3>
              <p>
                This is my Phase One Project for Flatiron School and after learing HTML we created a page that had at least two different listening commands.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1'>HTML</p>
              <p className='text-grey-800 py-1'>VS Code</p>
              <p className='text-grey-800 py-1'>Adobe Photoshop</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto rounded' src={phaseTwo} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Phase One Project
              </h3>
              <p>
                This is my Phase One Project for Flatiron School and after learing HTML we created a page that had at least two different listening commands.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1'>HTML</p>
              <p className='text-grey-800 py-1'>VS Code</p>
              <p className='text-grey-800 py-1'>Adobe Photoshop</p>
            </div><div className='text-center shadow-lg p-10 rounded-xl my-10'>
              <Image className='mx-auto rounded' src={phaseForth} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2'>
                Phase One Project
              </h3>
              <p>
                This is my Phase One Project for Flatiron School and after learing HTML we created a page that had at least two different listening commands.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1'>HTML</p>
              <p className='text-grey-800 py-1'>VS Code</p>
              <p className='text-grey-800 py-1'>Adobe Photoshop</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1'>Portfolio</h3>
            <p className='text-md py-20 leading-8 text-gray-800'>
              I have over 7 years of experience doing videography and photography for many different events. I've set-up live streams, work as grip on sets, have hands-on knowledge using all different types of cameras, and still growing my knoweldge. I graduated from Flatiron School in NYC with knowledge in HTML, Javascript, React, Sinatra, SQL, and Ruby on Rails. I use everything in the Adobe Suite for editing pictures, video, and graphic design work.
            </p>
          </div>
          <div className='flex'>
            <div className='m-2'><Image className='rounded-full ' src={shopButtafly} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={chyren} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={Dakota} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={Shoes} width={300} height={300}/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
