import Head from 'next/head';
import Image from 'next/image';
import phaseOne from '../public/Screen Shot 2022-11-29 at 3.52.06 PM.png'
import phaseTwo from '../public/Screen Shot 2022-11-29 at 3.54.00 PM.png'
import chyren from '../public/Screen Shot 2022-12-01 at 7.32.34 PM.png'
import Dakota from '../public/Screen Shot 2022-12-01 at 7.34.43 PM.png'
import Shoes from '../public/Screen Shot 2022-12-01 at 7.51.34 PM.png'
import shopButtafly from '../public/Screen Shot 2022-12-01 at 7.47.16 PM.png'
import phaseForth from '../public/Screen Shot 2022-11-29 at 3.56.46 PM.png'
import mikel from '../public/Screen Shot 2022-12-01 at 10.56.56 AM.png';
import {BsFillMoonStarsFill} from 'react-icons/bs';
import {AiFillInstagram, AiFillLinkedin, AiFillYoutube} from 'react-icons/ai';
import { useState } from 'react';

export default function Home() {

  const [darkMode, setDarkMode] = useState(false)

  return (
    <div className={ darkMode ? 'dark' : ''}>
      <Head>
        <title>Mike Dwyer Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=' bg-white px-10 md:px-20 lg:px:40 dark:bg-gray-900'>
        <section className="min-h-screen">
          <nav className=' py-10 mb-12 flex justify-between'>
            <h1 className='text-xl dark:text-white'>Michael Dwyer</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-gray-600'/>
              </li>
              <li><a className='bg-gradient-to-r from-cyan-600 to-sky-300 text-white px-4 py-2 rounded-md ml-8' href='https://docs.google.com/document/d/1jC6TNL4MFxPrtTbLDU6gih0fWAfggA32WixSNENxSPU'>Resume</a></li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl text-teal-500 font-medium md:text-7xl '>Michael Dwyer</h2>
            <h3 className='text-2xl py-2 md:text-3xl dark:text-gray-400'>Developer, Videographer, Photographer, and Graphic Designer</h3>
            <p className='text-md py-5 md:text-xl max-w-xl mx-auto leading-8 text-gray-800 dark:text-white'>Freelancer that provides services for programming, media coverage, and graphic designing needs. Join me down below and let's lock in some work!</p>
          </div>
          <div className='flex justify-items-center text-gray-600'>
            <div className='flex justify-items-center mx-auto text-5xl gap-16 pb-3'>
              <a href="https://www.instagram.com/officialmikelens/"><AiFillInstagram className='cursor-pointer'/></a>
              <a href="https://www.linkedin.com/in/michael-dwyer-2abb07104/"><AiFillLinkedin className='cursor-pointer'/></a>
              <a href="https://www.youtube.com/@mikedwyer360"><AiFillYoutube className='cursor-pointer'/></a>
            </div>
          </div>
          <div className='relative w-80 h-80 my-12 md:h-96 md:w-96 mx-auto'>
            <div><Image className='rounded-full' src={mikel} layout='fill' objectFit='cover'/></div>
          </div>
        </section>

        <section>
          <div className='text-center'>
            <h3 className='text-3xl dark:text-gray-400'>
              Services I Offer
            </h3>
            <p className='text-md py-20 leading-8 text-gray-800 dark:text-white'>
              I have over 7 years of experience doing videography and photography for many different events. I've set-up live streams, work as grip on sets, have hands-on knowledge using all different types of cameras, and still growing my knoweldge. I graduated from Flatiron School in NYC with knowledge in HTML, Javascript, React, Sinatra, SQL, and Ruby on Rails. I use everything in the Adobe Suite for editing pictures, video, and graphic design work.
            </p>
          </div>
          <div className='grid lg:grid-cols-3 gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 cursor-pointer'>
              <Image className='mx-auto rounded' src={phaseOne} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Phase One Project
              </h3>
              <p className='dark:text-white'>
                This is my Phase One Project for Flatiron School and after learing HTML we created a page that had at least two different listening commands. The first is the warning modal that pop-ups on the login, the second is when clicking on the Avenger character, and the third comes from Locate Avenger button. That button triggers the API that fetches a random location for the where Avanger is currently.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1 dark:text-white'>HTML</p>
              <p className='text-grey-800 py-1 dark:text-white'>VS Code</p>
              <p className='text-grey-800 py-1 dark:text-white'>Adobe Photoshop</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 cursor-pointer'>
              <Image className='mx-auto rounded' src={phaseTwo} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Phase Two Project
              </h3>
              <p className='dark:text-white'>
                This is my Phase Two Project for Flatiron School and ironically created a portfolio page with bookings capabilities. By creating slides of my photography work, a comment section for the home page, and make at least three client side routes to complete my requirements. The second and third page has Email JS triggered by the form submit button. The information is then sent to my email for bookings with the user's information.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1 dark:text-white'>Email JS</p>
              <p className='text-grey-800 py-1 dark:text-white'>React</p>
              <p className='text-grey-800 py-1 dark:text-white'>VS Code</p>
            </div><div className='text-center shadow-lg p-10 rounded-xl my-10 cursor-pointer'>
              <Image className='mx-auto rounded' src={phaseForth} width={500} height={500}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>
                Phase Four Project
              </h3>
              <p className='dark:text-white'>
                This is my Phase Four Project for Flatiron School, where I wanted to create a project that mixed fantasy league, and anime together. I used React for my frontend/client side and used Ruby on Rails for my backend to organize my data. With using context to clean up my code for logging in and joining leagues with your friends, user could make leagues, having full CRUD over the league or just play in a league they were invited to.
              </p>
              <h4 className=' py-4 text-teal-600'>
                Tools And Languages Used
              </h4>
              <p className='text-grey-800 py-1 dark:text-white'>React</p>
              <p className='text-grey-800 py-1 dark:text-white'>Ruby on Rails</p>
              <p className='text-grey-800 py-1 dark:text-white'>VS Code</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Media Portfolio</h3>
            <p className='text-md py-20 leading-8 text-gray-800 dark:text-white'>
              Here are some sample pictures of work I've done, with a bigger array of options to look through if you take a look at my Instagram. I have videos that I have shot, directed, edited all myself.So please feel free to take a look at my professional page's work and get a deeper dive into who I am through my Linkedin, YouTube, or resume.
            </p>
          </div>
          <div className='flex'>
            <div className='m-2'><Image className='rounded-full ' src={shopButtafly} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={chyren} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={Dakota} width={300} height={300}/></div>
            <div className='m-2'><Image className='rounded-full ' src={Shoes} width={300} height={300}/></div>
          </div>
        </section>
      </main>
    </div>
  )
}
